# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sbuilder.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'sbuilder.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0esbuilder.proto\x12\x08sbuilder\"\x1c\n\x08Question\x12\x10\n\x08question\x18\x01 \x01(\t\"\x1c\n\x0cTextStreamer\x12\x0c\n\x04text\x18\x01 \x01(\t2B\n\x08SBuilder\x12\x36\n\x04\x43hat\x12\x12.sbuilder.Question\x1a\x16.sbuilder.TextStreamer\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sbuilder_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QUESTION']._serialized_start=28
  _globals['_QUESTION']._serialized_end=56
  _globals['_TEXTSTREAMER']._serialized_start=58
  _globals['_TEXTSTREAMER']._serialized_end=86
  _globals['_SBUILDER']._serialized_start=88
  _globals['_SBUILDER']._serialized_end=154
# @@protoc_insertion_point(module_scope)
